// <auto-generated />
using System;
using Flauction.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Flauction.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20251013122856_initieleCreate")]
    partial class initieleCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Flauction.Models.Bod", b =>
                {
                    b.Property<int>("BodID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BodID"));

                    b.Property<decimal>("Bedrag")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Bieder")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("GebruikersID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tijdstip")
                        .HasColumnType("datetime2");

                    b.Property<int>("VeilingsproductID")
                        .HasColumnType("int");

                    b.HasKey("BodID");

                    b.HasIndex("GebruikersID");

                    b.HasIndex("VeilingsproductID");

                    b.ToTable("Bod");
                });

            modelBuilder.Entity("Flauction.Models.Dashboard", b =>
                {
                    b.Property<int>("DashboardID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DashboardID"));

                    b.Property<int>("VeilingsID")
                        .HasColumnType("int");

                    b.HasKey("DashboardID");

                    b.HasIndex("VeilingsID");

                    b.ToTable("Dashboard");
                });

            modelBuilder.Entity("Flauction.Models.Gebruiker", b =>
                {
                    b.Property<int>("GebruikersID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GebruikersID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Gebruikersnaam")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Wachtwoord")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("GebruikersID");

                    b.ToTable("Gebruiker");
                });

            modelBuilder.Entity("Flauction.Models.Veiling", b =>
                {
                    b.Property<int>("VeilingsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VeilingsID"));

                    b.Property<DateTime>("EindTijd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartTijd")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("VeilingmeesterID")
                        .HasColumnType("int");

                    b.HasKey("VeilingsID");

                    b.HasIndex("VeilingmeesterID");

                    b.ToTable("Veiling");
                });

            modelBuilder.Entity("Flauction.Models.Veilingsproduct", b =>
                {
                    b.Property<int>("VeilingsproductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VeilingsproductID"));

                    b.Property<string>("Aanvoerder")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Foto")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Hoeveelheid")
                        .HasColumnType("int");

                    b.Property<string>("Kenmerken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Prijs")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("VeilingsID")
                        .HasColumnType("int");

                    b.HasKey("VeilingsproductID");

                    b.HasIndex("VeilingsID");

                    b.ToTable("Veilingsproduct");
                });

            modelBuilder.Entity("Flauction.Models.Bod", b =>
                {
                    b.HasOne("Flauction.Models.Gebruiker", "Gebruiker")
                        .WithMany("Biedingen")
                        .HasForeignKey("GebruikersID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Flauction.Models.Veilingsproduct", "Veilingsproduct")
                        .WithMany("Biedingen")
                        .HasForeignKey("VeilingsproductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gebruiker");

                    b.Navigation("Veilingsproduct");
                });

            modelBuilder.Entity("Flauction.Models.Dashboard", b =>
                {
                    b.HasOne("Flauction.Models.Veiling", "Veiling")
                        .WithMany("Dashboards")
                        .HasForeignKey("VeilingsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Veiling");
                });

            modelBuilder.Entity("Flauction.Models.Veiling", b =>
                {
                    b.HasOne("Flauction.Models.Gebruiker", "Veilingmeester")
                        .WithMany("Veilingen")
                        .HasForeignKey("VeilingmeesterID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Veilingmeester");
                });

            modelBuilder.Entity("Flauction.Models.Veilingsproduct", b =>
                {
                    b.HasOne("Flauction.Models.Veiling", "Veiling")
                        .WithMany("Veilingsproducten")
                        .HasForeignKey("VeilingsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Veiling");
                });

            modelBuilder.Entity("Flauction.Models.Gebruiker", b =>
                {
                    b.Navigation("Biedingen");

                    b.Navigation("Veilingen");
                });

            modelBuilder.Entity("Flauction.Models.Veiling", b =>
                {
                    b.Navigation("Dashboards");

                    b.Navigation("Veilingsproducten");
                });

            modelBuilder.Entity("Flauction.Models.Veilingsproduct", b =>
                {
                    b.Navigation("Biedingen");
                });
#pragma warning restore 612, 618
        }
    }
}
