// <auto-generated />
using System;
using Flauction.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Flauction.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20251115153645_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Flauction.Models.Acceptance", b =>
                {
                    b.Property<int>("acceptance_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("acceptance_id"));

                    b.Property<decimal>("accepted_price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("accepted_quantity")
                        .HasColumnType("int");

                    b.Property<int>("tick_number")
                        .HasColumnType("int");

                    b.Property<DateTime>("time")
                        .HasColumnType("datetime2");

                    b.Property<int>("auction_id")
                        .HasColumnType("int");

                    b.Property<int>("auction_lot_id")
                        .HasColumnType("int");

                    b.Property<int>("company_id")
                        .HasColumnType("int");

                    b.HasKey("acceptance_id");

                    b.ToTable("Acceptance");
                });

            modelBuilder.Entity("Flauction.Models.Auction", b =>
                {
                    b.Property<int>("auction_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("auction_id"));

                    b.Property<decimal>("au_current_price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("end_time")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("final_price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("au_min_increment")
                        .HasColumnType("int");

                    b.Property<int>("start_price")
                        .HasColumnType("int");

                    b.Property<DateTime>("start_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("auctionmaster_id")
                        .HasColumnType("int");

                    b.Property<int>("plant_id")
                        .HasColumnType("int");

                    b.Property<int>("winner_company_id")
                        .HasColumnType("int");

                    b.HasKey("auction_id");

                    b.ToTable("Auction");
                });

            modelBuilder.Entity("Flauction.Models.AuctionClock", b =>
                {
                    b.Property<int>("auctionclock_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("auctionclock_id"));

                    b.Property<decimal>("ac_decrement_amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ac_final_call_seconds")
                        .HasColumnType("int");

                    b.Property<decimal>("ac_tick_interval_seconds")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("auction_id")
                        .HasColumnType("int");

                    b.HasKey("auctionclock_id");

                    b.ToTable("AuctionClock");
                });

            modelBuilder.Entity("Flauction.Models.AuctionLot", b =>
                {
                    b.Property<int>("auctionlot_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("auctionlot_id"));

                    b.Property<int>("containers_in_lot")
                        .HasColumnType("int");

                    b.Property<int>("fustcode")
                        .HasColumnType("int");

                    b.Property<int>("min_pickup")
                        .HasColumnType("int");

                    b.Property<int>("remaining_quantity")
                        .HasColumnType("int");

                    b.Property<int>("total_quantity")
                        .HasColumnType("int");

                    b.Property<int>("unit_per_container")
                        .HasColumnType("int");

                    b.Property<int>("auction_id")
                        .HasColumnType("int");

                    b.Property<int>("image_id")
                        .HasColumnType("int");

                    b.HasKey("auctionlot_id");

                    b.ToTable("AuctionLot");
                });

            modelBuilder.Entity("Flauction.Models.AuctionMaster", b =>
                {
                    b.Property<int>("auctionmaster_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("auctionmaster_id"));

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("am_email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("am_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("am_password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("am_phone")
                        .HasColumnType("int");

                    b.HasKey("auctionmaster_id");

                    b.ToTable("AuctionMaster");
                });

            modelBuilder.Entity("Flauction.Models.Company", b =>
                {
                    b.Property<int>("company_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("company_id"));

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bicswift")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("iban")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("c_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("c_password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("postalcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("vat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("company_id");

                    b.ToTable("Company");
                });

            modelBuilder.Entity("Flauction.Models.ContactPerson", b =>
                {
                    b.Property<int>("contactperson_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("contactperson_id"));

                    b.Property<int>("company_id")
                        .HasColumnType("int");

                    b.Property<string>("cp_email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cp_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("cp_phone")
                        .HasColumnType("int");

                    b.HasKey("contactperson_id");

                    b.ToTable("ContactPerson");
                });

            modelBuilder.Entity("Flauction.Models.Media", b =>
                {
                    b.Property<int>("media_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("media_id"));

                    b.Property<string>("alt_text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("is_primary")
                        .HasColumnType("bit");

                    b.Property<string>("url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("plant_id")
                        .HasColumnType("int");

                    b.HasKey("media_id");

                    b.ToTable("Media");
                });

            modelBuilder.Entity("Flauction.Models.Plant", b =>
                {
                    b.Property<int>("plant_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("plant_id"));

                    b.Property<string>("category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("desc")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("form")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("maturity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("min_stem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("productname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("quality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stems_bunch")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("supplier_id")
                        .HasColumnType("int");

                    b.HasKey("plant_id");

                    b.ToTable("Plant");
                });

            modelBuilder.Entity("Flauction.Models.Supplier", b =>
                {
                    b.Property<int>("supplier_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("supplier_id"));

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("desc")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("iban")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("s_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("postalcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("supplier_id");

                    b.ToTable("Supplier");
                });
#pragma warning restore 612, 618
        }
    }
}
