// <auto-generated />
using System;
using Flauction.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Flauction.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20251126143735_databasev5")]
    partial class databasev5
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Flauction.Models.Acceptance", b =>
                {
                    b.Property<int>("acceptance_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("acceptance_id"));

                    b.Property<decimal>("acc_accepted_price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("acc_accepted_quantity")
                        .HasColumnType("int");

                    b.Property<int>("acc_tick_number")
                        .HasColumnType("int");

                    b.Property<DateTime>("acc_time")
                        .HasColumnType("datetime2");

                    b.Property<int>("auction_id")
                        .HasColumnType("int");

                    b.Property<int>("auction_lot_id")
                        .HasColumnType("int");

                    b.Property<int>("company_id")
                        .HasColumnType("int");

                    b.HasKey("acceptance_id");

                    b.HasIndex("auction_id");

                    b.HasIndex("auction_lot_id");

                    b.HasIndex("company_id");

                    b.ToTable("Acceptance");
                });

            modelBuilder.Entity("Flauction.Models.Auction", b =>
                {
                    b.Property<int>("auction_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("auction_id"));

                    b.Property<DateTime>("au_end_time")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("au_final_price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("au_min_price")
                        .HasColumnType("int");

                    b.Property<int>("au_start_price")
                        .HasColumnType("int");

                    b.Property<DateTime>("au_start_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("au_status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("auctionmaster_id")
                        .HasColumnType("int");

                    b.Property<int>("plant_id")
                        .HasColumnType("int");

                    b.HasKey("auction_id");

                    b.HasIndex("auctionmaster_id");

                    b.HasIndex("plant_id");

                    b.ToTable("Auction");
                });

            modelBuilder.Entity("Flauction.Models.AuctionClock", b =>
                {
                    b.Property<int>("auctionclock_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("auctionclock_id"));

                    b.Property<decimal>("ac_decrement_amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ac_final_call_seconds")
                        .HasColumnType("int");

                    b.Property<decimal>("ac_tick_interval_seconds")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("auction_id")
                        .HasColumnType("int");

                    b.HasKey("auctionclock_id");

                    b.HasIndex("auction_id");

                    b.ToTable("AuctionClock");
                });

            modelBuilder.Entity("Flauction.Models.AuctionLot", b =>
                {
                    b.Property<int>("auctionlot_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("auctionlot_id"));

                    b.Property<int>("al_containers_in_lot")
                        .HasColumnType("int");

                    b.Property<int>("al_fustcode")
                        .HasColumnType("int");

                    b.Property<int>("al_min_pickup")
                        .HasColumnType("int");

                    b.Property<int>("al_remaining_quantity")
                        .HasColumnType("int");

                    b.Property<int>("al_total_quantity")
                        .HasColumnType("int");

                    b.Property<int>("al_unit_per_container")
                        .HasColumnType("int");

                    b.Property<int>("auction_id")
                        .HasColumnType("int");

                    b.Property<int>("image_id")
                        .HasColumnType("int");

                    b.HasKey("auctionlot_id");

                    b.HasIndex("auction_id");

                    b.HasIndex("image_id");

                    b.ToTable("AuctionLot");
                });

            modelBuilder.Entity("Flauction.Models.AuctionMaster", b =>
                {
                    b.Property<int>("auctionmaster_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("auctionmaster_id"));

                    b.Property<string>("am_address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("am_email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("am_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("am_password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("am_phone")
                        .HasColumnType("int");

                    b.HasKey("auctionmaster_id");

                    b.ToTable("AuctionMaster");
                });

            modelBuilder.Entity("Flauction.Models.Company", b =>
                {
                    b.Property<int>("company_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("company_id"));

                    b.Property<string>("c_address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("c_bicswift")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("c_country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("c_iban")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("c_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("c_password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("c_postalcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("c_vat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("company_id");

                    b.ToTable("Company");
                });

            modelBuilder.Entity("Flauction.Models.ContactPerson", b =>
                {
                    b.Property<int>("contactperson_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("contactperson_id"));

                    b.Property<int>("company_id")
                        .HasColumnType("int");

                    b.Property<string>("cp_email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cp_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("cp_phone")
                        .HasColumnType("int");

                    b.HasKey("contactperson_id");

                    b.HasIndex("company_id");

                    b.ToTable("ContactPerson");
                });

            modelBuilder.Entity("Flauction.Models.Media", b =>
                {
                    b.Property<int>("media_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("media_id"));

                    b.Property<string>("m_alt_text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("m_is_primary")
                        .HasColumnType("bit");

                    b.Property<string>("m_url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("plant_id")
                        .HasColumnType("int");

                    b.HasKey("media_id");

                    b.HasIndex("plant_id");

                    b.ToTable("Media");
                });

            modelBuilder.Entity("Flauction.Models.Plant", b =>
                {
                    b.Property<int>("plant_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("plant_id"));

                    b.Property<string>("p_category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("p_desc")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("p_form")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("p_maturity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("p_min_stem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("p_productname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("p_quality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("p_stems_bunch")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("supplier_id")
                        .HasColumnType("int");

                    b.HasKey("plant_id");

                    b.HasIndex("supplier_id");

                    b.ToTable("Plant");
                });

            modelBuilder.Entity("Flauction.Models.Supplier", b =>
                {
                    b.Property<int>("supplier_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("supplier_id"));

                    b.Property<string>("s_address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("s_country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("s_desc")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("s_email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("s_iban")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("s_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("s_postalcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("supplier_id");

                    b.ToTable("Supplier");
                });

            modelBuilder.Entity("Flauction.Models.Acceptance", b =>
                {
                    b.HasOne("Flauction.Models.Auction", null)
                        .WithMany()
                        .HasForeignKey("auction_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Acceptance_Auction");

                    b.HasOne("Flauction.Models.AuctionLot", null)
                        .WithMany()
                        .HasForeignKey("auction_lot_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Acceptance_AuctionLot");

                    b.HasOne("Flauction.Models.Company", null)
                        .WithMany()
                        .HasForeignKey("company_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Acceptance_Company");
                });

            modelBuilder.Entity("Flauction.Models.Auction", b =>
                {
                    b.HasOne("Flauction.Models.AuctionMaster", null)
                        .WithMany()
                        .HasForeignKey("auctionmaster_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Auction_AuctionMaster");

                    b.HasOne("Flauction.Models.Plant", null)
                        .WithMany()
                        .HasForeignKey("plant_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Auction_Plant");
                });

            modelBuilder.Entity("Flauction.Models.AuctionClock", b =>
                {
                    b.HasOne("Flauction.Models.Auction", null)
                        .WithMany()
                        .HasForeignKey("auction_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_AuctionClock_Auction");
                });

            modelBuilder.Entity("Flauction.Models.AuctionLot", b =>
                {
                    b.HasOne("Flauction.Models.Auction", null)
                        .WithMany()
                        .HasForeignKey("auction_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_AuctionLot_Auction");

                    b.HasOne("Flauction.Models.Media", null)
                        .WithMany()
                        .HasForeignKey("image_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_AuctionLot_Media");
                });

            modelBuilder.Entity("Flauction.Models.ContactPerson", b =>
                {
                    b.HasOne("Flauction.Models.Company", null)
                        .WithMany()
                        .HasForeignKey("company_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ContactPerson_Company");
                });

            modelBuilder.Entity("Flauction.Models.Media", b =>
                {
                    b.HasOne("Flauction.Models.Plant", null)
                        .WithMany()
                        .HasForeignKey("plant_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Media_Plant");
                });

            modelBuilder.Entity("Flauction.Models.Plant", b =>
                {
                    b.HasOne("Flauction.Models.Supplier", null)
                        .WithMany()
                        .HasForeignKey("supplier_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Plant_Supplier");
                });
#pragma warning restore 612, 618
        }
    }
}
